add capella SDK
codex-team/capella.nodejs pull request #1
Opened 2018-01-18 20:33 UTC by vovaksenov99

2018-01-18 21:24 UTC, gohabereg requested changes

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +  capellaSDK.uploadImageToCapella = function (imagePath, callback) {
Очень длинное название. Лучше просто `uploadFile`

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +      let req = request.post('https://capella.pics/upload', callback);
В callback попадает строка. Лучше создать декоратор, которые распарсит json. А еще лучше всяких проверок туда напихать. Если не доступен сайт или еще чего

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +      form.append('file', fs.createReadStream(imagePath));
Что будет, если путь до файла неверный?

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +  capellaSDK.uploadImageToCapellaURL = function (URL, callback) {
uploadByURL

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +    catch (exception) {
Думаю, лучше выкидывать эксепшены наружу, а пользователь уже сам разберется что с ними делать

2018-01-18 21:24 UTC, gohabereg commented on src/capellaSDK.js
> +module.exports = function (capellaSDK) {
Может оформить как класс?

2018-01-18 21:24 UTC, gohabereg commented on package.json
> +  "description": "Capella SDK for Node.js",
Node SDK for Capella

2018-01-18 21:26 UTC, neSpecc requested changes

2018-01-18 21:26 UTC, neSpecc commented on package.json
> +  "name": "capellasdk",
capella-pics

2018-01-18 21:26 UTC, neSpecc commented on package.json
> +  "description": "Capella SDK for Node.js",
Module for useful image uploading with capella.pics

2018-01-18 21:26 UTC, neSpecc commented on package.json
> +  "main": "src/capellaSDK.js",
capella.js или sdk.js

2018-01-18 21:26 UTC, neSpecc commented on package.json
> +    "capella"
, image-uploading, uploader, image-filters

2018-01-18 21:26 UTC, neSpecc commented on package.json
> +  "author": "https://ifmo.su",
CodeX (https://ifmo.su)

2018-01-18 21:26 UTC, neSpecc commented on src/capellaSDK.js
> +      form.append('file', fs.createReadStream(imagePath));
а что она возвратит в этом случае?

2018-01-18 21:26 UTC, neSpecc commented on src/capellaSDK.js
> +   */
нужно задокументировать возвращаемое значение

2018-01-18 21:26 UTC, neSpecc commented on src/capellaSDK.js
> +   * @param {String} imagePath local path to image
поставь дефисы перед описанием

2018-01-18 21:26 UTC, neSpecc commented on src/capellaSDK.js
> +      form.append('link', URL);
тоже не хватает возвращаемого значения

2018-01-18 21:29 UTC, vovaksenov99 commented on src/capellaSDK.js
> +   */
Не возвращаю больше значение

2018-01-18 23:28 UTC, gohabereg requested changes

2018-01-18 23:28 UTC, gohabereg commented on src/capella.js
> +      let req = request.post('https://capella.pics/upload', (error, resp, body) => {
Ссылку можно вынести в переменную

2018-01-18 23:28 UTC, gohabereg commented on src/capella.js
> +      let req = request.post('https://capella.pics/upload', (error, resp, body) => {
Функцию декоратор тоже можно отдельно вынести, чтобы в двух местах не повторять

2018-01-18 23:28 UTC, gohabereg commented on src/capella.js
> +      throw  exception;
Зачем ловить и сразу кидать? Можно тогда не ловить.. Или как-то их обрабатывать, например возвращать объект с читабельными полями

2018-01-18 23:28 UTC, gohabereg commented on src/capella.js
> +      form.append('link', URL);
Функции отличаются одной строчкой. Может их можно как-то объединить?

2018-01-19 07:25 UTC, neSpecc requested changes

2018-01-19 07:25 UTC, neSpecc commented on src/capella.js
> +   *
Description is missed

2018-01-19 07:25 UTC, neSpecc commented on src/capella.js
> +   * @param {String} - json json string with server answer
JSON string with the server response

2018-01-19 07:25 UTC, neSpecc commented on src/capella.js
> +   * @return {any | *} - json or string with error
{object|string} - parsed response or error message

2018-01-19 07:25 UTC, neSpecc commented on src/capella.js
> +  getAnswer (json) {
parseResponse

2018-01-19 07:25 UTC, neSpecc commented on src/capella.js
> +      throw exception;
meaningless `try`, can be removed

2018-01-19 11:45 UTC, talyguryn reviewed
добавь .eslintrc и поправь стиль кода

2018-01-19 11:46 UTC, talyguryn reviewed
добавь readme с полной инструкцией по установке и использованию

2018-01-19 11:46 UTC, neSpecc requested changes

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> +    this.CAPELLA_UPLOAD_LINK = 'https://capella.pics/upload';
endpoint

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> +   * @param {String} - json JSON string with the server response
> – json

json –

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> +      else {
wrong linebreak

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> +  {
wrong line break

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> + */
add link to the Capella repository

2018-01-19 11:46 UTC, neSpecc commented on src/capella.js
> +      callback(this.parseResponse(body));
let response = this.parseResponse(body);

callback(response);

2018-01-19 13:51 UTC, neSpecc requested changes

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +capella = new capella;
new Capella();

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +let capella = require('capella-pics');
Capella

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +Return string error if operation failed or [capella response](https://github.com/codex-team/capella#upload-api) if all was successful
Return Capella Response object if everything is ok, otherwise returns Error message.

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +If you have not valid path, not valid internet connection and etc. you get exception
Exception will be thrown in cases of invalid file, inactive internet connection etc.

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +Return string error if operation failed or [capella response](https://github.com/codex-team/capella#upload-api) if all was successful
Describe Response object here.

2018-01-19 13:51 UTC, neSpecc commented on README.md
> +
describe callback function

2018-01-19 14:47 UTC, neSpecc requested changes

2018-01-19 14:47 UTC, neSpecc commented on src/capella.js
> +            let response = this.parseResponse(body);
вот тут надо поставить try. И В случае ошибки вызывать callback с параметром error

2018-01-19 19:33 UTC, gohabereg requested changes

2018-01-19 19:33 UTC, gohabereg commented on README.md
> +Return Capella response [Describe Response object here](https://github.com/codex-team/capella#upload-api) object if everything is ok, otherwise returns Error message.
У тебя есть плагин, поддерживающий md разметку? Посмотри как это будет выглядеть на гитхабе
![image](https://user-images.githubusercontent.com/23050529/35167976-68778d34-fd68-11e7-9d58-b1b6d8ee7fbd.png)

2018-01-19 19:33 UTC, gohabereg commented on README.md
> +Exception will be thrown in cases of invalid file, inactive internet connection etc.
Вроде же в итоге не выбрасываются эксепшены

2018-01-19 19:33 UTC, gohabereg commented on README.md
> +capella.uploadFileByURL('https://capella.pics/public/app/svg/capella-logo.svg', function (resp) {
Капелла не поддерживает svg)

2018-01-19 19:33 UTC, gohabereg commented on src/capella.js
> +   * @param {String} - imagePath local path to image
Дефис нужно ставить после имени параметра

2018-01-19 19:33 UTC, gohabereg commented on src/capella.js
> +   * @param {String} json - json JSON string with the server response
json JSON?

2018-01-19 21:47 UTC, gohabereg approved these changes

2018-01-20 09:26 UTC, khaydarov requested changes

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +    /**
блок с комментами

```javascript
/**
 * code desc
 * params
 * returns
 */
 function() { }
```

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +   * Get and parse answer from server
answer => response

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +     * Define endpoint URL fo Capella uploader
for

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +   * Create request for post image to Capella
тут бы тоже поправить блок с комментами

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +   * Create request for post image to Capella
что значит "for post image". HTTP POST request

2018-01-20 09:26 UTC, khaydarov commented on src/capella.js
> +   * Callback argument description
Callback arguments description

2018-01-20 09:31 UTC, khaydarov submitted a review, later dismissed

2018-01-20 09:31 UTC, khaydarov commented on README.md
> +//upload by local path
upload from local path/ upload via local file path ...

2018-01-20 09:31 UTC, khaydarov commented on README.md
> +Return [Capella response](https://github.com/codex-team/capella#upload-api) object if everything is ok, otherwise returns Error message.
лучше оформить в виде таблицы

Server response

| param | type | description|
| success | string | response status|
| message | string | response message|

2018-01-20 09:43 UTC, vovaksenov99 commented on src/capella.js
> +    /**
Здесь нет return, params. Это пустой конструктор

2018-01-20 09:43 UTC, vovaksenov99 commented on src/capella.js
> +   * Get and parse answer from server
Синоним одного и того же

2018-01-20 09:44 UTC, vovaksenov99 commented on src/capella.js
> +   * Create request for post image to Capella
Значит что я создаю запрос для отправки изображения на капеллу

2018-01-20 09:44 UTC, vovaksenov99 commented on src/capella.js
> +   * Callback argument description
Аргумент один

2018-01-20 09:45 UTC, vovaksenov99 commented on README.md
> +Return [Capella response](https://github.com/codex-team/capella#upload-api) object if everything is ok, otherwise returns Error message.
Лучше чтобы видели как именно и в каком формате возвращает. Таблица такого представления не дает

2018-01-20 09:58 UTC, khaydarov commented on src/capella.js
> +    /**
я про /** */

2018-01-20 09:59 UTC, khaydarov commented on src/capella.js
> +   * Create request for post image to Capella
POST это HTTP запрос. Ты же создаешь HTTP POST запрос

2018-01-20 10:03 UTC, khaydarov commented on src/capella.js
> +   * Create request for post image to Capella
ок, понял

2018-01-20 12:30 UTC, khaydarov approved these changes

2018-01-20 13:59 UTC, neSpecc requested changes

2018-01-20 13:59 UTC, neSpecc commented on src/capella.js
> +                    'message': 'Invalid JSON format'
пользователю это ничего не даст. Такая ошибка упадет если что-то не так с капеллой. Нужно дать это понять

2018-01-20 14:31 UTC, neSpecc approved these changes

2018-01-20 15:01 UTC, talyguryn requested changes

2018-01-20 15:01 UTC, talyguryn commented on README.md
> +
Абзац с инструкцией по установке отсутствует

2018-01-20 15:01 UTC, talyguryn commented on README.md
> +//upload by URL
Хотя бы пробел после // поставь

2018-01-20 15:01 UTC, talyguryn commented on README.md
> +```
И блок с лицензией лишним не будет

2018-01-20 15:01 UTC, talyguryn commented on package.json
> +  "scripts": {
Можно удалить

2018-01-20 15:01 UTC, talyguryn commented on src/capella.js
> +     *
Лишняя строка

2018-01-20 15:01 UTC, talyguryn commented on src/capella.js
> +     * @return {Function} - request query
Точно функцию возвращает?

2018-01-20 15:01 UTC, talyguryn commented on src/capella.js
> +                    'message': 'Invalid JSON format'
Инвалид json респонс

2018-01-20 15:46 UTC, vovaksenov99 commented on src/capella.js
> +     * @return {Function} - request query
Насколько я знаю, да

2018-01-20 16:00 UTC, talyguryn approved these changes

2018-01-20 16:07 UTC, merged