Add configuration parameter with custom endpoint to the constructor
codex-team/capella.nodejs pull request #10
Opened 2018-09-16 08:27 UTC by n0str

2018-09-16 09:23 UTC, neSpecc requested changes

2018-09-16 09:23 UTC, neSpecc commented on src/capella.js
> +        this.endpoint = configuration.endpoint || 'https://capella.pics/upload';
будет ошибка при пустом конструкторе

2018-09-16 09:29 UTC, neSpecc approved these changes

2018-09-16 09:59 UTC, talyguryn requested changes

2018-09-16 09:59 UTC, talyguryn commented on src/capella.js
> +    constructor(configuration={}) {
it is not a python. add spaces pls

`configuration = {}`

2018-09-16 09:59 UTC, talyguryn commented on src/capella.js
> +    constructor(configuration={}) {
and define type of `configuration` object

2018-09-18 06:59 UTC, talyguryn approved these changes

2018-09-18 07:09 UTC, merged